[package]
name = "spline-editor"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
edition = "2018"

[dependencies]
cgmath = "0.17"
luminance = "0.36"
luminance-derive = "0.4"
luminance-glfw = "0.10"
splines = { version = "2", features = ["impl-cgmath"] }
